name: yad2k
channels:
- defaults
dependencies:
- mkl=2017.0.1=0
- numpy=1.12.0=py36_0
- openssl=1.0.2k=0
- pip=9.0.1=py36_1
- python=3.6.0=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
prefix: /data/titan/a/allan/anaconda3/envs/yad2k

